name: Build standalone version

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
    build:
        name: New Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup aftman
              uses: ok-nick/setup-aftman@v0.4.2
            
            - name: Install Wally dependencies
              run: |
                wally install

            - name: Build standalone
              run: |
                rojo build standalone.project.json --output build/standalone.rbxm

            - name: Create release
              id: create_release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ github.ref }}
                draft: true
                body_path: docs/changelog.md
                files: "build/standalone.rbxm"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}